### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by Y3K-dev** [phocus/vscode#1]
i'm using VSCodium (version 1.67.2) and can't download the extension.
the errror - `Can't install 'phisch.phocus-vscode' extension because it is not compatible with the current version of VSCodium (version 1.67.2).`
i tried with normal VSCode also, didn't work

OS - NixOS

**Comment by phisch** [comment]
Thanks for reporting. When I created the theme, I set the dependency for the latest version of vscode, which was `1.70.0` at the time. It is defined here: https://github.com/phocus/vscode/blob/main/package.json#L41
My current version of vscode is:
```sh
phisch@laptop ~ ❯ code --version
1.71.0
```

What distro do you use? `1.67.2` is from april this year, so it's a bit outdated: https://code.visualstudio.com/updates/v1_67

**Comment by Y3K-dev** [comment]
> Thanks for reporting. When I created the theme, I set the dependency for the latest version of vscode, which was `1.70.0` at the time. It is defined here: https://github.com/phocus/vscode/blob/main/package.json#L41 My current version of vscode is:
> 
> ```shell
> phisch@laptop ~ ❯ code --version
> 1.71.0
> ```
> 
> What distro do you use? `1.67.2` is from april this year, so it's a bit outdated: https://code.visualstudio.com/updates/v1_67

:eyes: got the theme working, i'm using nix. but it was downloading from stable (1.67.2) and i installed from unstable branch(1.70.0).

Thanks!
